### ISSUE TITLE
Support for Morphed `Texcoord_n` and `Color_n` Attributes

### ISSUE THREAD

**Issue by ptasev** [vpenades/SharpGLTF#116] opened 2021-12-13 22:40 UTC
Looks like the glTF spec added the optional Texcoord_n, and Color_n morph targets. Should this be supported in `IMorphTargetBuilder` and `IMeshDecoder`?

> Client implementations SHOULD support at least three attributes — POSITION, NORMAL, and TANGENT — for morphing. Client implementations MAY optionally support morphed TEXCOORD_n and/or COLOR_n attributes.
https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#morph-targets

I have a file format I'm converting to that supports Texcoord_0 and Color_0 morphing, however it's not an often used feature.

**Comment by vpenades** [comment] 2021-12-14 07:44
yes, it's a useful feature, and I'm surprised it was not part of the spec since the very beginning.

Although I don't think I'll be able to work on it for the next release, I'll add it to the roadmap, though.

**Comment by ptasev** [comment] 2022-06-07 01:37
I noticed a bug with the MorphTargetBuilder.
https://github.com/vpenades/SharpGLTF/blob/f34511e1d656c006fa2b68311ed0c4b5de6dbf1b/src/SharpGLTF.Toolkit/Geometry/MorphTargetBuilder.cs#L88-L103

On Line 90, it checks for geometry to be default, but this is bad in the case that material is not default. Should probably check that both geometry and material are default before entering the if block.

**Comment by vpenades** [comment] 2022-06-13 07:13
@ptasev that exception is a bug.

What's going on is that by default, the library bakes the vertices into strided vertices. But strided vertices are not well suited for meshes that contain morph targets, so the library automatically resolves to split vertices (one accessor per vertex attribute) when it encounters geometry with morph targets.

But for some reason, it's failing to notice the mesh has morph targets.

I'll look into it

**Comment by vpenades** [comment] 2022-06-13 08:03
@ptasev I've just pushed a small improvement that covers this and lets the test pass; I would suggest you to add your test to SharpGltf.ThirdParty.Tests  under your name.cs

anyway, morph targets definitely require more test cases so I'll keep reviewing the code related to it

**Comment by ptasev** [comment] 2022-06-13 09:27
Thanks, I'll add the test soon. It seems the test passes now, but if I add the following lines at the end then it fails:
```csharp
AttachmentInfo
    .From("ColorMorphingMultiPrim.glb")
    .WriteFile(f => model.Save(f.FullName, new WriteSettings() { Validation = ValidationMode.Skip }));
AttachmentInfo
    .From("ColorMorphingMultiPrim.gltf")
    .WriteFile(f => model.Save(f.FullName, new WriteSettings() { Validation = ValidationMode.Skip }));
```

**Comment by vpenades** [comment] 2022-06-13 20:15
It seems my previous fix didn't provide the expected results.

Forcing the exporter to write a non existing morph target in the first primitive produces this output:

```json
"meshes": [
    {
      "name": "mesh",
      "primitives": [
        {
          "attributes": {
            "POSITION": 0,
            "COLOR_0": 1
          },
          "indices": 2,
          "material": 0,
          "targets": []
        },
        {
          "attributes": {
            "POSITION": 3,
            "COLOR_0": 4
          },
          "indices": 5,
          "material": 1,
          "targets": [
            {
              "COLOR_0": 6
            }
          ]
        }
      ]
    }
```` 

The first primitive has an empty targets array which is what's producing the problem, and the second one is correct.

Now, the question is, should all primitives in a mesh have target matching target entries, even if empty? in which case fixing the array would be trivial.

Otherwise, if all primitives need to have matching morph targets, things will get more complicated... I guess we'll have to dig into the specs

**Comment by vpenades** [comment] 2022-06-13 20:48
It seems we're not alone: https://github.com/KhronosGroup/glTF/issues/2154

**Comment by vpenades** [comment] 2022-06-13 20:55
```json
"targets": [ {} ]
```
I think the problem is that, not only empty arrays are disallowed, also empty objects ?

**Comment by ptasev** [comment] 2022-06-13 20:57
That I'm not sure of, but if the first part I highlighted is correct, then that means we don't need to include all attributes specified by the base mesh, and in that case it will interpreted as using original values.  If we don't have to include all attributes, I take that to mean that we don't need to include any if the intent is to make no changes to original values.

But that's all theoretical from reading the spec.

**Comment by vpenades** [comment] 2022-06-13 21:18
`[ {} ]` gives an error in gltf validator.

I would need an example from khronos to see which is the valid way of writing this, because from the specs its not clear at all

**Comment by ptasev** [comment] 2022-06-15 04:04
Not sure if you saw this on Discord, but currently there's no way to get `IMaterialTransform` from `DrawableInstance`.

**Comment by ptasev** [comment] 2022-06-25 21:07
Looks like if the morph target doesn't have vertex deltas, then calculating smooth normals fails (line 87). The vertex deltas have a count of 0.
https://github.com/vpenades/SharpGLTF/blob/d9fdfa92b98f70afc579912908ea79b12bf3a03d/src/SharpGLTF.Core/Runtime/MeshDecoder.Schema2.cs#L60-L90

**Comment by vpenades** [comment] 2022-06-26 08:39
@ptasev Technically, normals can be derived from the surface triangles, and the tangets can be derived from the surface UVs and the normals... and that is true for both source geometry and morph geometry.

In normal cirumstances, you usually create meshes in two ways: from other formats, where normals and tangents are usually available, or from procedurally generated geometry. In this latter case it's usually very painful to require the developer to generate its own normals (or maybe I am naive by wanting to be too helpful)... but as you noticed, this didn't take into account morph targets.

I'm not sure what to do in this case.... ideally, it could be possible to generate the normals and tangents for the morph targets, but it would require quite a lot of code and development time... so maybe the alternative for now is to simply hack it to not throw exceptions.

What do you think?

**Comment by ptasev** [comment] 2022-06-26 18:40
Part of what makes the library so useful is a lot of helper classes on top of glTF to help work with the data. I think this is a good feature to have. `MeshDecoder` is a huge time saver.

My earlier comment is in regards to the case where morph targets don't have vertex deltas and normal deltas. It doesn't make sense to generate normals, and instead they can be copied from the base mesh if I'm not mistaken.

**Comment by vpenades** [comment] 2022-07-02 16:10
> Looks like if the morph target doesn't have position deltas, then calculating smooth normals fails (line 87). The position deltas is null.

@ptasev I couldn't replicate that scenario, could you write a test case for it?

I thick after the morph targets and a few other issues are resolved, I'll publish new nugets

**Comment by ptasev** [comment] 2022-07-03 14:29
To reproduce, add this line to the end of the test I recently added to the repo:
`var aaa = model.LogicalMeshes[0].Decode();`

**Comment by vpenades** [comment] 2022-09-26 20:52
I believe this issue is completed, so closing it down.

**Closed by vpenades** 2022-09-26 20:52 UTC
